# Generated by Django 4.2.27 on 2025-12-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parceiros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvaliacaoMercado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estrelas", models.PositiveSmallIntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "compra",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacao",
                        to="parceiros.compra",
                    ),
                ),
                (
                    "mercado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parceiros.mercado",
                    ),
                ),
            ],
        ),
    ]
